from __future__ import annotations

import shutil
import unittest
from pathlib import Path

import pandas as pd

from thess_geo_analytics.pipelines.BuildNdviMonthlyStatisticsPipeline import (
    BuildNdviMonthlyStatisticsPipeline,
    BuildNdviMonthlyStatisticsParams,
)
from thess_geo_analytics.utils.RepoPaths import RepoPaths
from tests.fixtures.generators.MiniNdviCompositeGenerator import (
    MiniNdviCompositeConfig,
    MiniNdviCompositeGenerator,
)


class RepoPathsOverride:
    """
    Redirect RepoPaths.OUTPUTS/TABLES/FIGURES to a test root.
    All outputs end up under tests/fixtures/generated/... and are kept.
    """

    def __init__(self, new_root: Path) -> None:
        self.new_root = new_root.resolve()
        self._orig_outputs = RepoPaths.OUTPUTS
        self._orig_tables = RepoPaths.TABLES
        self._orig_figures = RepoPaths.FIGURES

    def __enter__(self):
        RepoPaths.OUTPUTS = self.new_root / "outputs"
        RepoPaths.TABLES = RepoPaths.OUTPUTS / "tables"
        RepoPaths.FIGURES = RepoPaths.OUTPUTS / "figures"
        RepoPaths.OUTPUTS.mkdir(parents=True, exist_ok=True)
        RepoPaths.TABLES.mkdir(parents=True, exist_ok=True)
        RepoPaths.FIGURES.mkdir(parents=True, exist_ok=True)
        return self

    def __exit__(self, exc_type, exc, tb):
        RepoPaths.OUTPUTS = self._orig_outputs
        RepoPaths.TABLES = self._orig_tables
        RepoPaths.FIGURES = self._orig_figures


class BuildNdviMonthlyStatisticsPipelineTest(unittest.TestCase):
    """
    E2E-ish test for BuildNdviMonthlyStatisticsPipeline.

    It uses synthetic NDVI composites:

      outputs/cogs/ndvi_2024-01_el522.tif
      outputs/cogs/ndvi_2024-02_el522.tif
      outputs/cogs/ndvi_2024-Q1_el522.tif

    and checks that:
      - ndvi_period_stats.csv is created
      - nvdi_timeseries.parquet and ndvi_timeseries.parquet exist
      - ndvi_timeseries.png exists

    All artifacts are written under:
      tests/fixtures/generated/ndvi_monthly_stats/outputs/...
    and are kept after the test.
    """

    def setUp(self) -> None:
        self.test_root = Path("tests/fixtures/generated/ndvi_monthly_stats").resolve()
        if self.test_root.exists():
            shutil.rmtree(self.test_root)
        self.test_root.mkdir(parents=True, exist_ok=True)

    # No tearDown: we keep the artifacts on disk

    def test_monthly_stats_and_timeseries(self) -> None:
        aoi_id = "el522"

        with RepoPathsOverride(self.test_root):
            # 1) Generate synthetic NDVI composites
            cfg = MiniNdviCompositeConfig(
                root=self.test_root,
                aoi_id=aoi_id,
                periods=["2024-01", "2024-02", "2024-Q1"],
                height=8,
                width=8,
            )
            gen = MiniNdviCompositeGenerator(cfg)
            generated_files = gen.generate()  # this returns a list[Path]

            # Sanity: some files were created
            self.assertTrue(
                generated_files,
                f"No NDVI COGs generated by MiniNdviCompositeGenerator in {self.test_root}",
            )

            # Locate COG directory via RepoPaths (which is overridden)
            from thess_geo_analytics.utils.RepoPaths import RepoPaths as RP2

            cogs_dir = RP2.OUTPUTS / "cogs"
            self.assertTrue(
                cogs_dir.exists(),
                f"COGs directory does not exist: {cogs_dir}",
            )
            self.assertTrue(
                list(cogs_dir.glob("ndvi_*_el522.tif")),
                f"No NDVI COGs found in {cogs_dir}",
            )

            # 2) Build params for the pipeline
            params = BuildNdviMonthlyStatisticsParams(
                aoi_id=aoi_id,
                stats_csv=RP2.table("ndvi_period_stats.csv"),
                out_parquet=RP2.table("nvdi_timeseries.parquet"),
                out_parquet_canonical=RP2.table("ndvi_timeseries.parquet"),
                out_fig=RP2.figure("ndvi_timeseries.png"),
            )

            # 3) Run pipeline
            pipe = BuildNdviMonthlyStatisticsPipeline()
            ts_parquet, fig_path = pipe.run(params)

            # 4) Artifacts exist
            self.assertTrue(
                params.stats_csv.exists(), f"Missing period stats CSV: {params.stats_csv}"
            )
            self.assertTrue(
                ts_parquet.exists(), f"Missing time series Parquet: {ts_parquet}"
            )
            self.assertTrue(
                params.out_parquet_canonical.exists(),
                f"Missing canonical Parquet: {params.out_parquet_canonical}",
            )
            self.assertTrue(
                fig_path.exists(), f"Missing NDVI time series figure: {fig_path}"
            )

            # 5) Quick schema checks
            df_stats = pd.read_csv(params.stats_csv)
            self.assertIn("period", df_stats.columns)
            self.assertIn("mean_ndvi", df_stats.columns)
            self.assertIn("median_ndvi", df_stats.columns)

            df_ts = pd.read_parquet(ts_parquet)
            self.assertIn("time", df_ts.columns)
            self.assertIn("mean_ndvi", df_ts.columns)
            self.assertIn("median_ndvi", df_ts.columns)
            self.assertGreater(len(df_ts), 0, "Empty NDVI time series")


if __name__ == "__main__":
    unittest.main()